namespace ProjectLasVegas.Code
{
    public class Desafio
    {
        //Verficar por erros de ortografia antes de publicar
        public static string[] Shared = new string[] { "Cante e dance uma canção do Justin Bieber!",
            "Deixe a pessoa a mais perto de você fazer uma transformação em você!",
            "Deixe uma pessoa de sua escolha pintar as suas unhas!",
            "Sussurre pelo resto desta partida!",
            "Você não pode falar até alguém falar o seu nome pelo resto da partida.",
            "Pelo resto da partida, você tem que terminar tudo o que fala com uma gargalhada falsa.",
            "Dê na pessoa a sua esquerda um beijo na bochecha!",
            "Dance lentamente com a pessoa a sentada a sua frente",
            "Nas próximas 3 rodadas, você tem que se mover em slow motion.",
            "Vá ao Facebook e encontre a última postagem no mural que você recebeu. Responda-a com: 'Não, você está errado'.",
            "Ligue para um de seus irmãos e declare alguma coisa que você admire nele ou nela.",
            "Faça a dança do siri!",
            "Cante a sua música favorita!",
            "Vista a sua roupa do lado contrário pelo resto da partida!",
            "Faça a pessoa sentada a mais perto de você rir em 30 segundos.",
            "Você não pode dizer 'Sim' ou 'Não' pelo resto do jogo!",
            "Vire 5 copos de água!",
            "Faça 20 flexões!",
            "Ligue par a último número discado no seu telefone e declare que você 'finalmente decidiu trocar ela pela Elza do Frozen'",
            "Massageie o couro cabeludo da pessoa sentada a sua direita!",
            "Ligue para um número randômico e finja que a pessoa que atendeu o telefone ligou para você e não o contrário!",
            "Jogue um beijo para a pessoa a sua frente!",
            "Sussurre um segredo para a pessoa sentada a sua frente!",
            "Deixe a pessoa a sua esquerda fazer cosquinha por 15 segundos!",
            "Imite uma pessoa desta sala, e deixe os outros adivinharem quem é!",
            "Envie uma mensagem de texto para o último número que você discou perguntando 'Qual é o seu problema?'",
            "Você tem que pular em uma perna só toda vez que tiver que andar pelo resto do jogo!",
            "Faça 20 abdominais!",
            "Adicione 'Junior' após o seu sobrenome no seu perfil do Facebook!",
            "Remova as suas meias!",
            "A próxima vez que você tiver que peidar, o faça bem alto!",
            "A próxima vez que o seu telefone tocar, o atenda com 'Pizzaria Papa Pepe, eu posso anotar o seu pedido...?'.",
            "Termine as suas mensagens de texto com 'lol #sqn' pelo resto da noite!",
            "Diga 'Eu não gosto de admitir, mas...' antes de toda a verdade que você responder pelo resto da noite.",
            "Sua sorte! Você pode dar a próxima consequência que você pegar para qualquer um desta sala!",
            "Ajude um desenvolvedor esforçado... escreva um bom comentário para o aplicativo #VerdadeouConsequência! ;-)",
            "Ligue para o último número que você discou e peça para te ligar às 7:00AM da próxima manhã para te acordar! ",
            "Você tem que atender todos os telefones que tocarem (não só o seu) pelo resto da noite.",
            "Envie uma mensagem de texto para o seu chefe: 'Qual a boa d hj?'",
            "Pense em uma palavra que ninguém poderá falar até o fim do jogo (ex. 'a' ou 'bebida'). Quem falar essa palavra irá participar da próxima consequência." };

        //Verficar por erros de ortografia antes de publicar
        public static string[] AtClass = new string[] { "Troque a sua camisa com uma pessoa do sexo oposto!",
            "Use suas meias nas suas orelhas pelo resto da partida.",
            "Esvazie a sua carteira, bolsos e bolsa e explique seus conteúdos!",
            "Leia em voz alta a última mensagem de texto que você recebeu.",
            "Mande uma mensagem de texto para o seu pai pedindo emprestado '50 pratas e uma marreta'...",
            "Bata na porta da sala do lado e fuja...",
            "Coloque um aviso na sua porta anunciando uma 'Festa do World of Warcraft esta sexta-feira! TRAGA O SEU PRÓPRIO COMPUTADOR!'",
            "Leia em voz alta o último e-mail que você recebeu.",
            "Configure seu celular para despertar às 6:00 AM da manhã seguinte!",
            "No Facebook, curta três fotos de uma paixão antiga sua!",
            "Ligue para a última pessoa que te ligou e peça perdão pelo 'que aconteceu'.",
            "Diga ao seu professor para 'Falar baixo, droga!'",
            "Cante e toque uma guitarra de mentira no tom de sua escolha!",
            "Consequência em Grupo: Todo mundo revele a cor da sua roupa íntima! Mostre se alguém duvidar.",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, 'Me mudando para a Tailândia. Doações são bem-vindas.'",
            "Escolha uma vítima que deve enviar uma solicitação de 'Noivado' no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Pegue o telefone de outro jogador e configure um alarme aleatório no calendário dele. Ele não pode ser alterado! ",
            "Faça outro jogador tirar uma foto da unha do dedão do pé e enviá-la via SMS para alguém que não está presente, com a legenda, 'Isto é herpes?' ",
            "Escolha uma vítima para postar o status: 'Alguém sabe onde posso pegar um pouco de LSD?'",
            "Escolha duas pessoas no seu grupo para 'casar' no Facebook. Também poste uma foto deles como 'casal'. ",
            "Escolha alguém para enviar um SMS para a última pessoa que eles contataram: 'Qual é a coisa mais diabólica que eu já fiz?' ",
            "Escolha alguém que deverá raspar metade da sua sobrancelha esquerda. Se ele (a) recusar, ele (a) DEVERÁ fazer o próximo castigo. ",
            "Consequência em Grupo: Todo mundo revele a cor da sua roupa íntima! Mostre se alguém duvidar.",
            "Deixe uma pessoa da sala te espancar!",
            "Troque o seu sobrenome no Facebook para 'Junior, Jr.'",
            "Troque o seu primeiro nome no Facebook para 'Billie-Ray.'",
            "Leia em voz alta todas as mensagens de texto que você receber até o final da noite!",
            "Você tem que fazer a próxima consequência que alguém pegar junto com ele ou ela!",
            "Encontre um anúncio no Mercado Livre apresentando pneus de carros. Envie um e-mail para o vendedor perguntando 'Eles são bons para perseguições de carro?'",
            "Toda vez que o seu telefone tocar pelo resto da noite, você tem que atendê-lo com 'Fã Clube Oficial da Celine Dion'.",
            "Troque a sua imagem de perfil do Facebook por uma foto do Michael Jackson e coloque a legenda 'TE AMO PARA SEMPRE! MEU HERÓI!!!'",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, 'Me mudando para a Tailândia. Doações são bem-vindas.'",
            "Escolha uma vítima que deve enviar uma solicitação de 'Noivado' no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Pegue o telefone de outro jogador e configure um alarme aleatório no calendário dele. Ele não pode ser alterado! ",
            "Dê um chupão em qualquer parte do corpo da pessoa que o grupo escolher.",
            "Escolha alguém que deve colocar um cubo de gelo dentro da calça dela por vinte segundos.",
            "Roube uma coisa da pessoa no grupo pelo resto da noite (ex. um artigo de roupa, celular, etc.).",
            "Escolha alguém para criar um grupo falso no Facebook (ex. Libere os Vampiros da Prisão Injusta do Governo!) e faça-o convidar ao menos doze amigos.",
            "Escolha alguém que deve te dar uma massagem nos próximos cinco minutos.   ",
            "Pense em um apelido idiota para a pessoa mais próxima de você e escreva na testa dele (a).",
            "Do celular da pessoa mais perto de você, escolha dez contatos para enviar um SMS com o seguinte: 'Você acabou de ganhar um cruzeiro grátis para as Bahamas! Envie ‘Férias’ para este número para resgatá-lo!'",
            "Faça a assinatura de outro jogador numa lista eletrônica de e-mail (ex. horóscopo ou medicamento para disfunção erétil).",
            "Escolha alguém com um iPhone. Altere três palavras nos atalhos do teclado. Por exemplo, faça de um jeito que toda vez que ele (a) apertar 'Está bem' aparecer 'Estou vomitando.'",
            "Escolha alguém que deve morder uma moeda. (Mas não engula). ",
            "Escolha alguém que deverá usar apenas sinais de mão para se comunicar. ",
            "Invente uma fofoca boba sobre alguém da sala e poste no Twitter.",
            "Faça o upload de uma foto de um tamanduá e marque alguém da sala que mais lembra um tamanduá.",
            "Escolha um jogador que só pode andar de costas pelo resto do jogador (ex. para ir ao banheiro). ",
            "Dê um beijo no pescoço da pessoa que está mais perto de você.",
            "Envie uma mensagem para seu/sua ex: 'Vamos tentar de novo nesse verão?' ",
            "Você é a brisa de verão. Sopre suavemente no ouvido da pessoa a sua escolha. ",
            "Finja que o dedo de outro jogador é um sorvete e lamba.  ",
            "Finja que está colocando protetor solar em você mesmo de forma sensual.  ",
            "Dispa sua roupa até ficar com as roupas íntimas e desfile.",
            "Faça de conta que você está cortando a grama e diga para todo o mundo imaginar que você está nu.  ",
            "Jogue uma moeda. Se der cara beije a pessoa à esquerda, se der coroa beije a pessoa à direita.  ",
            "Relaxe deitando-se no chão e escolhendo uma pessoa para lhe fazer uma massagem relaxante.  ",
            "Dê para a pessoa, a escolha do grupo, sua melhor cantada de férias. Ela pode pontuar você pelo seu esforço.",
            "Termine a frase como quiser: 'A minha coisa favorita para fazer num dia quente de verão é …' ",
            "O verão do amor tem tudo a ver com igualdade. Beije alguém do mesmo sexo.  ",
            "Você inventou uma nova posição sexual chamada O Verão Escaldante – mostre como funciona.  ",
            "Imite uma gaivota.  ",
            "Abra a janela e grite: 'Eu gosto de estar deitado nu ao sol'",
            "É divertido dançar toda a noite – mostre para nós sua dança mais sexy.  ",
            "Faça dez abdominais.",
            "Descreva perfeitamente cada pessoa na sala usando somente uma palavra.  ",
            "Coloque um pouco de água num copo e depois jogue em sua cabeça.",
            "Esfrie pondo um cubo de gelo em suas calças.  ",
            "Escolha uma pessoa na sala e sente em seus joelhos até que seja novamente sua vez de jogar. ",
            "O calor de verão está chegando. Tire uma peça de roupa à sua escolha de uma maneira sedutora.  ",
            "Espalhe o amor beijando toda a gente na sala!  ",
            "As noites foram feitas para dançar; mostre para todo o mundo seus melhores movimentos de dança.  ",
            "Vá lá fora e grite: 'EU SOU SPANKY, O MONSTRO SEXY DO PECADO DE VERÃO'. ",
            "Fala uma imitação de um animal fazendo sexo – você pode escolher o animal!  ",
            "Poste no Facebook a mensagem: 'Eu acho que sou um totalmente sexy na praia – Curta se você concorda'.",
            "Grite o nome de todas as partes privadas que você consiga lembrar.",
            "Durante uma hora use sua roupa íntima por cima de sua roupa.  ",
            "Pegue uma flor e coloque no cabelo de alguém. Terá de usar a flor durante o resto do jogo.  ",
            "Sopre seu beijo mais sexy para cada pessoa na sala.  ",
            "O sol clareia seu cabelo e você parece a Marilyn Monroe – cante Happy Birthday para alguém na sala usando sua voz mais sexy. ",
            "Invente uma música sobre o verão e cante.  ",
            "Poste no seu status do Facebook: 'Quem deve ser meu caso de Verão? Aceito todas as sugestões.' ",
            "Escolha um jogador e reencene uma cena famosa de beijo.",
            "Escolha outro jogador e faça um duelo de strip-tease. Um de cada vez vão tirando uma peça de roupa. O primeiro a recusar perde – e tem de girar a garrafa e escolher DESAFIO.  ",
            "Faça uma imitação de alguém caminhando com as partes privadas queimadas pelo sol.  ",
            "Faça uma imitação de um cachorro com sede num dia quente.",
            "Saia da sala, tire sua roupa interior e coloque na mesa onde terá de ficar durante o resto do jogo.  ",
            "Invente a nova dança louca e ensine para todo o mundo que está na sala.  ",
            "Você é a estrela de um filme pornográfico rodado na praia. Qual o nome do filme?  ",
            "Descreva como você imagina que a pessoa a sua frente é quando está nua. ",
            "Fique em pé até que seja novamente sua vez de jogar. ",
            "Finja que está nadando pela sala.",
            "Desabotoe e solte todas as suas roupas. ",
            "Leia uma mensagem sexy que você tenha em seu celular. Se não tem nenhuma, então envie uma.  ",
            "Vá molhar seu cabelo. Você não pode secar durante dez minutos.  ",
            "O verão é uma época para tirar a roupa: exiba uma parte de seu corpo que você não costuma mostrar.  ",
            "Dê um beijo em alguém do mesmo sexo. Se você é tímido, pode beijar na bochecha!",
            "Imite um caranguejo correndo na praia." };
        
        //Verficar por erros de ortografia antes de publicar
        public static string[] Couple = new string[] { "Esvazie a sua carteira, bolsos e bolsa e explique seus conteúdos!",
            "Troque um artigo de roupa com a pessoa a sua esquerda.",
            "Troque um artigo de roupa com uma pessoa que o grupo escolher.",
            "Escolha alguém para jogar a próxima rodada sem estar usando as calças. ",
            "Dê a você mesmo uma massagem sensual.",
            "Consequência em Grupo: Todo mundo troque uma peça de roupa com outra pessoa desta sala!",
            "Deixe uma pessoa da sala te espancar!",
            "Pesquise no Google 'Bondage machine', selecione as imagens, e explique em voz alta para todo mundo da sala o que você vê.",
            "Dê um chupão em qualquer parte do corpo da pessoa que o grupo escolher.",
            "Escolha alguém que deve colocar um cubo de gelo dentro da calça dela por vinte segundos.",
            "Roube uma coisa da pessoa no grupo pelo resto da noite (ex. um artigo de roupa, celular, etc.)." };

        //Verficar por erros de ortografia antes de publicar
        public static string[] Family = new string[] { "Deixe o grupo te enfaixar com papel higiênico como uma múmia!",
            "Abra a janela, incline-se para fora e cante o hino nacional bem alto!",
            "Engula uma colher cheia de canela!",
            "Abra a janela e tente fazer com que alguém da rua acene para você!",
            "Espanque a pessoa a sua frente!",
            "Leia em voz alta a última mensagem de texto que você recebeu.",
            "Mande uma mensagem de texto para o seu pai pedindo emprestado '50 pratas e uma marreta'...",
            "Bata na porta do seu vizinho e fuja...",
            "Coloque um aviso na sua porta anunciando uma 'Festa do World of Warcraft esta sexta-feira! TRAGA O SEU PRÓPRIO COMPUTADOR!'",
            "Leia em voz alta o último e-mail que você recebeu.",
            "Configure seu celular para despertar às 6:00 AM da manhã seguinte!",
            "No Facebook, curta três fotos de uma paixão antiga sua!",
            "Ligue para a última pessoa que te ligou e peça perdão pelo 'que aconteceu'.",
            "Cante e toque uma guitarra de mentira no tom de sua escolha!",
            "Ligue para o último número que você discou e peça para te ligar às 7:00AM da próxima manhã para te acordar!",
            "Pegue o telefone de outro jogador e configure um alarme aleatório no calendário dele. Ele não pode ser alterado! ",
            "Escolha uma vítima para postar o status: 'Alguém sabe onde posso pegar uma marreta?'",
            "Escolha duas pessoas no seu grupo para 'casar' no Facebook. Também poste uma foto deles como 'casal'. ",
            "Escolha alguém para enviar um SMS para a última pessoa que eles contataram: 'Qual é a coisa mais diabólica que eu já fiz?' ",
            "Escolha uma pessoa do grupo para cortar um pedaço do seu cabelo. Boa sorte em encontrar alguém em que você confie... ",
            "Escolha outro jogador que deverá molhar e ensaboar o cabelo dele na pia. ",
            "Entorne um quarto de um copo de água no colo da pessoa sentada a sua esquerda.",
            "Troque o seu sobrenome no Facebook para 'Junior, Jr.'",
            "Troque o seu primeiro nome no Facebook para 'Billie-Ray.'",
            "Leia em voz alta todas as mensagens de texto que você receber até o final da noite!",
            "Você tem que fazer a próxima consequência que alguém pegar junto com ele ou ela!",
            "Encontre um anúncio no Mercado Livre apresentando pneus de carros. Envie um e-mail para o vendedor perguntando 'Eles são bons para perseguições de carro?'",
            "Toda vez que o seu telefone tocar pelo resto da noite, você tem que atendê-lo com 'Fã Clube Oficial da Celine Dion'.",
            "Troque a sua imagem de perfil do Facebook por uma foto do Michael Jackson e coloque a legenda 'TE AMO PARA SEMPRE! MEU HERÓI!!!'",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, 'Me mudando para a Tailândia. Doações são bem-vindas.'",
            "Escolha uma vítima que deve enviar uma solicitação de 'Noivado' no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Pegue o telefone de outro jogador e configure um alarme aleatório no calendário dele. Ele não pode ser alterado! ",
            "Roube uma coisa da pessoa no grupo pelo resto da noite (ex. um artigo de roupa, celular, etc.).",
            "Escolha alguém para dar um trote em um membro da família ligando para ele e fingindo ser o Batman pedindo perdão. ",
            "Escolha alguém para criar um grupo falso no Facebook (ex. Libere os Vampiros da Prisão Injusta do Governo!) e faça-o convidar ao menos doze amigos.",
            "Escolha alguém que deve te dar uma massagem nos próximos cinco minutos.   ",
            "Do celular da pessoa mais perto de você, escolha dez contatos para enviar um SMS com o seguinte: 'Você acabou de ganhar um cruzeiro grátis para as Bahamas! Envie ‘Férias’ para este número para resgatá-lo!'",
            "Faça a assinatura de outro jogador numa lista eletrônica de e-mail (ex. horóscopo ou medicamento para disfunção erétil).",
            "Escolha alguém com um iPhone. Altere três palavras nos atalhos do teclado. Por exemplo, faça de um jeito que toda vez que ele (a) apertar 'Está bem' aparecer 'Estou vomitando.'",
            "Escolha alguém que deve morder uma moeda. (Mas não engula). ",
            "Escolha alguém que deverá usar apenas sinais de mão para se comunicar. ",
            "Escolha alguém que deve usar um saco na sua cabeça (com buracos para os olhos e boca) até o fim da noite. ",
            "Invente uma fofoca boba sobre alguém da sala e poste no Twitter.",
            "Faça o upload de uma foto de um tamanduá e marque alguém da sala que mais lembra um tamanduá.",
            "Escolha um jogador que só pode andar de costas pelo resto do jogador (ex. para ir ao banheiro). " };

        //Verficar por erros de ortografia antes de publicar
        public static string[] Friends = new string[] { "Troque a sua camisa com uma pessoa do sexo oposto!",
            "Deixe o grupo te enfaixar com papel higiênico como uma múmia!",
            "Abra a janela, incline-se para fora e cante o hino nacional bem alto!",
            "Abra a geladeira e pegue três líquidos randomicamente. Faça um drink com eles e prove!",
            "Engula uma colher cheia de canela!",
            "Abra a janela e tente fazer com que alguém da rua acene para você!",
            "Bata na porta do seu vizinho e pergunte se ele “tem um pouco de rum ilegal”?",
            "Espanque a pessoa a sua frente!",
            "Coloque um gelo nas suas calças e deixe derreter!",
            "Dê uma volta na sua vizinhança vestindo apenas um roupão de banho e sapatos.",
            "Dê um amasso apaixonado com um bicho de pelúcia por 15 segundos!",
            "Remova as meias da pessoa na sua frente usando apenas a sua boca!",
            "Deixe todo mundo fazer um drink usando três quaisquer ingredientes – e então beba!",
            "Esvazie a sua carteira, bolsos e bolsa e explique seus conteúdos!",
            "Sussurre sensualmente seu nome no ouvido da pessoa sentada a sua direita.",
            "Leia em voz alta a última mensagem de texto que você recebeu.",
            "Mande uma mensagem de texto para o seu pai pedindo emprestado '50 pratas e uma marreta'...",
            "Bata na porta do seu vizinho e fuja...",
            "Tome um gole de cada bebida na mesa a sua frente!",
            "Coloque um aviso na sua porta anunciando uma 'Festa do World of Warcraft esta sexta-feira! TRAGA O SEU PRÓPRIO COMPUTADOR!'",
            "Leia em voz alta o último e-mail que você recebeu.",
            "Configure seu celular para despertar às 6:00 AM da manhã seguinte!",
            "No Facebook, curta três fotos de uma paixão antiga sua!",
            "Ligue para a última pessoa que te ligou e peça perdão pelo “que aconteceu”.",
            "Diga ao seu vizinho para “Falar baixo, droga! ”",
            "Tire uma foto da bebida na sua frente com o seu celular e envie a foto para a pessoa mais velha da sua agenda telefônica. Escreva: 'Saúde!'",
            "Dê nomes de cavaleiros falsos para cada um da sala - ex. 'McBolasGrandes', 'Sir Beber-rão'.",
            "Cante e toque uma guitarra de mentira no tom de sua escolha!",
            "Sussurre uma sacanagem no ouvido da pessoa sentada a sua direita!",
            "Consequência em Grupo: Todo mundo revele a cor da sua roupa íntima! Mostre se alguém duvidar.",
            "Deixe uma pessoa da sala te espancar!",
            "Troque o seu sobrenome no Facebook para 'Junior, Jr.'",
            "Troque o seu primeiro nome no Facebook para 'Billie-Ray.'",
            "Pesquise no Google 'Bondage machine', selecione as imagens, e explique em voz alta para todo mundo da sala o que você vê.",
            "A próxima vez que você usar o banheiro, você não pode fechar a porta.",
            "Leia em voz alta todas as mensagens de texto que você receber até o final da noite!",
            "Você tem que fazer a próxima consequência que alguém pegar junto com ele ou ela!",
            "Encontre um anúncio no Mercado Livre apresentando pneus de carros. Envie um e-mail para o vendedor perguntando 'Eles são bons para perseguições de carro?'",
            "Toda vez que o seu telefone tocar pelo resto da noite, você tem que atendê-lo com 'Fã Clube Oficial da Celine Dion'.",
            "Troque a sua imagem de perfil do Facebook por uma foto do Michael Jackson e coloque a legenda 'TE AMO PARA SEMPRE! MEU HERÓI!!!'",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, “Me mudando para a Tailândia. Doações são bem-vindas. ”",
            "Escolha uma vítima que deve enviar uma solicitação de “Noivado” no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Escolha alguém que tem que vestir as roupas do lado avesso pelo resto da noite. ",
            "Troque um artigo de roupa com a pessoa a sua esquerda.",
            "Troque um artigo de roupa com uma pessoa que o grupo escolher.",
            "Pegue o telefone de outro jogador e configure um alarme aleatório no calendário dele. Ele não pode ser alterado! ",
            "Escolha uma vítima para postar o status: “Alguém sabe onde posso pegar um pouco de LSD? ”",
            "Escolha duas pessoas no seu grupo para “casar” no Facebook. Também poste uma foto deles como “casal”. ",
            "Escolha alguém para enviar um SMS para a última pessoa que eles contataram: “Qual é a coisa mais diabólica que eu já fiz? ” ",
            "Escolha uma pessoa do grupo para cortar um pedaço do seu cabelo. Boa sorte em encontrar alguém em que você confie... ",
            "Escolha alguém que deverá raspar metade da sua sobrancelha esquerda. Se ele(a) recusar, ele(a) DEVERÁ fazer o próximo castigo. ",
            "Entorne um quarto de um copo de água no colo da pessoa sentada a sua esquerda.",
            "Dê um chupão em qualquer parte do corpo da pessoa que o grupo escolher.",
            "Escolha alguém que deve colocar um cubo de gelo dentro da calça dela por vinte segundos.",
            "Roube uma coisa da pessoa no grupo pelo resto da noite (ex. um artigo de roupa, celular, etc.).",
            "Escolha alguém para criar um grupo falso no Facebook (ex. Libere os Vampiros da Prisão Injusta do Governo!) e faça-o convidar ao menos doze amigos.",
            "Escolha alguém que deve sentar no colo de outro jogador pelas próximas duas rodadas. ",
            "Escolha alguém que deve te dar uma massagem nos próximos cinco minutos.   ",
            "Escolha alguém que deve vestir a roupa íntima dele por cima das roupas até o fim da noite.",
            "Mande outro jogador ficar de pé olhando um canto da parede pela próxima rodada. A pessoa deve rebolar toda vez que alguém xingar. ",
            "Pense em um apelido idiota para a pessoa mais próxima de você e escreva na testa dele(a).",
            "Escolha um jogador que só pode andar de costas pelo resto do jogador (ex. para pegar outra bebida, para ir ao banheiro). " };

        //Verficar por erros de ortografia antes de publicar
        public static string[] Park = new string[] { "Troque a sua camisa com uma pessoa do sexo oposto!",
            "Cante o hino nacional bem alto!",
            "Esvazie a sua carteira, bolsos e bolsa e explique seus conteúdos!",
            "Dê a volta na praça só de cueca",
            "Leia em voz alta a última mensagem de texto que você recebeu.",
            "Mande uma mensagem de texto para o seu pai pedindo emprestado '50 pratas e uma marreta'...",
            "Coloque um aviso na sua porta anunciando uma 'Festa do World of Warcraft esta sexta-feira! TRAGA O SEU PRÓPRIO COMPUTADOR!'",
            "Leia em voz alta o último e-mail que você recebeu.",
            "Configure seu celular para despertar às 6:00 AM da manhã seguinte!",
            "No Facebook, curta três fotos de uma paixão antiga sua!",
            "Ligue para a última pessoa que te ligou e peça perdão pelo “que aconteceu”.",
            "Consequência em Grupo: Todo mundo revele a cor da sua roupa íntima! Mostre se alguém duvidar.",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, “Me mudando para a Tailândia. Doações são bem-vindas. ”",
            "Escolha uma vítima que deve enviar uma solicitação de “Noivado” no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Faça outro jogador tirar uma foto da unha do dedão do pé e enviá-la via SMS para alguém que não está presente, com a legenda, “Isto é herpes? ” ",
            "Escolha uma vítima para postar o status: “Alguém sabe onde posso pegar um pouco de LSD? ”",
            "Escolha duas pessoas no seu grupo para “casar” no Facebook. Também poste uma foto deles como “casal”. ",
            "Escolha alguém para enviar um SMS para a última pessoa que eles contataram: “Qual é a coisa mais diabólica que eu já fiz? ” ",
            "Escolha uma pessoa do grupo para cortar um pedaço do seu cabelo. Boa sorte em encontrar alguém em que você confie... ",
            "Escolha alguém para beijar uma pessoa a sua escolha.",
            "Escolha alguém para beijar, de língua, uma pessoa a sua escolha.",
            "Escolha alguém para beijar, só um selinho, uma pessoa a sua escolha.",
            "Consequência em Grupo: Todo mundo revele a cor da sua roupa íntima! Mostre se alguém duvidar.",
            "Deixe uma pessoa da praça te espancar!",
            "Leia em voz alta todas as mensagens de texto que você receber até o final da noite!",
            "Você tem que fazer a próxima consequência que alguém pegar junto com ele ou ela!",
            "Encontre um anúncio no Mercado Livre apresentando pneus de carros. Envie um e-mail para o vendedor perguntando 'Eles são bons para perseguições de carro?'",
            "Toda vez que o seu telefone tocar pelo resto da noite, você tem que atendê-lo com 'Fã Clube Oficial da Celine Dion'.",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, “Me mudando para a Tailândia. Doações são bem-vindas. ”",
            "Escolha uma vítima que deve enviar uma solicitação de “Noivado” no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Roube uma coisa da pessoa no grupo pelo resto da noite (ex. um artigo de roupa, celular, etc.).",
            "Escolha alguém para criar um grupo falso no Facebook (ex. Libere os Vampiros da Prisão Injusta do Governo!) e faça-o convidar ao menos doze amigos.",
            "Mande outro jogador ficar de pé olhando um canto da parede pela próxima rodada. A pessoa deve rebolar toda vez que alguém xingar. ",
            "Escolha alguém para correr uma volta em torno do prédio que vocês estão. (Se for tarde da noite, escolha dois amigos para ir – sistema de amigo!)",
            "Escolha um jogador que só pode andar de costas pelo resto do jogador (ex. para pegar outra bebida, para ir ao banheiro). " };

        //Verficar por erros de ortografia antes de publicar
        public static string[] TheBests = new string[] { "Esvazie a sua carteira, bolsos e bolsa e explique seus conteúdos!",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, “Me mudando para a Tailândia. Doações são bem-vindas. ”",
            "Escolha uma vítima que deve enviar uma solicitação de “Noivado” no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Escolha alguém que tem que vestir as roupas do lado avesso pelo resto da noite. ",
            "Troque um artigo de roupa com a pessoa a sua esquerda.",
            "Troque um artigo de roupa com uma pessoa que o grupo escolher.",
            "Faça outro jogador tirar uma foto da unha do dedão do pé e enviá-la via SMS para alguém que não está presente, com a legenda, “Isto é herpes? ” ",
            "Escolha uma vítima para postar o status: “Alguém sabe onde posso pegar um pouco de LSD? ”",
            "Escolha duas pessoas no seu grupo para “casar” no Facebook. Também poste uma foto deles como “casal”. ",
            "Escolha alguém para enviar um SMS para a última pessoa que eles contataram: “Qual é a coisa mais diabólica que eu já fiz? ” ",
            "Escolha uma pessoa do grupo para cortar um pedaço do seu cabelo. Boa sorte em encontrar alguém em que você confie... ",
            "Escolha alguém que deverá raspar metade da sua sobrancelha esquerda. Se ele (a) recusar, ele (a) DEVERÁ fazer o próximo castigo. ",
            "Escolha alguém para jogar a próxima rodada sem estar usando as calças. ",
            "Escolha alguém para beijar uma pessoa a sua escolha.",
            "Escolha alguém para beijar, de língua, uma pessoa a sua escolha.",
            "Escolha alguém para beijar, só um selinho, uma pessoa a sua escolha.",
            "Escolha outro jogador para fazer um strip-tease até a roupa íntima. ",
            "Dê a você mesmo uma massagem sensual.",
            "Consequência em Grupo: Todo mundo troque uma peça de roupa com outra pessoa desta sala!",
            "Deixe uma pessoa da sala te espancar!",
            "Troque o seu sobrenome no Facebook para 'Junior, Jr.'",
            "Troque o seu primeiro nome no Facebook para 'Billie-Ray.'",
            "Pesquise no Google 'Bondage machine', selecione as imagens, e explique em voz alta para todo mundo da sala o que você vê.",
            "A próxima vez que você usar o banheiro, você não pode fechar a porta.",
            "Leia em voz alta todas as mensagens de texto que você receber até o final da noite!",
            "Você tem que fazer a próxima consequência que alguém pegar junto com ele ou ela!",
            "Encontre um anúncio no Mercado Livre apresentando pneus de carros. Envie um e-mail para o vendedor perguntando 'Eles são bons para perseguições de carro?'",
            "Toda vez que o seu telefone tocar pelo resto da noite, você tem que atendê-lo com 'Fã Clube Oficial da Celine Dion'.",
            "Troque a sua imagem de perfil do Facebook por uma foto do Michael Jackson e coloque a legenda 'TE AMO PARA SEMPRE! MEU HERÓI!!!'",
            "Escolha alguém para postar no status do Facebook status ou no Twitter, “Me mudando para a Tailândia. Doações são bem-vindas. ”",
            "Escolha uma vítima que deve enviar uma solicitação de “Noivado” no Facebook para alguém que ele (a) não fala há alguns anos. ",
            "Escolha alguém que tem que vestir as roupas do lado avesso pelo resto da noite. ",
            "Troque um artigo de roupa com a pessoa a sua esquerda.",
            "Troque um artigo de roupa com uma pessoa que o grupo escolher.",
            "Escolha uma vítima para postar o status: “Alguém sabe onde posso pegar um pouco de LSD? ”",
            "Escolha duas pessoas no seu grupo para “casar” no Facebook. Também poste uma foto deles como “casal”. ",
            "Escolha alguém para enviar um SMS para a última pessoa que eles contataram: “Qual é a coisa mais diabólica que eu já fiz? ” ",
            "Escolha uma pessoa do grupo para cortar um pedaço do seu cabelo. Boa sorte em encontrar alguém em que você confie... ",
            "Escolha alguém que deverá raspar metade da sua sobrancelha esquerda. Se ele (a) recusar, ele (a) DEVERÁ fazer o próximo castigo. ",
            "Entorne um quarto de um copo de água no colo da pessoa sentada a sua esquerda.",
            "Dê um chupão em qualquer parte do corpo da pessoa que o grupo escolher.",
            "Escolha alguém que deve colocar um cubo de gelo dentro da calça dela por vinte segundos.",
            "Roube uma coisa da pessoa no grupo pelo resto da noite (ex. um artigo de roupa, celular, etc.).",
            "Você sabe o e-mail de login no Facebook de alguém? Desabilite temporariamente a conta dele colocando a senha errada várias vezes. ",
            "Escolha alguém para criar um grupo falso no Facebook (ex. Libere os Vampiros da Prisão Injusta do Governo!) e faça-o convidar ao menos doze amigos.",
            "Escolha uma vítima que deve lamber um sabão em barra. ",
            "Escolha alguém que deve sentar no colo de outro jogador pelas próximas duas rodadas. ",
            "Escolha alguém que deve te dar uma massagem nos próximos cinco minutos.   ",
            "Escolha alguém que deve vestir a roupa íntima dele por cima das roupas até o fim da noite.",
            "Mande outro jogador ficar de pé olhando um canto da parede pela próxima rodada. A pessoa deve rebolar toda vez que alguém xingar. ",
            "Bata na pessoa a sua frente.",
            "Pense em um apelido idiota para a pessoa mais próxima de você e escreva na testa dele (a).",
            "Do celular da pessoa mais perto de você, escolha dez contatos para enviar um SMS com o seguinte: “Você acabou de ganhar um cruzeiro grátis para as Bahamas! Envie ‘Férias’ para este número para resgatá-lo! ”",
            "Faça a assinatura de outro jogador numa lista eletrônica de e-mail (ex. horóscopo ou medicamento para disfunção erétil).",
            "Escolha alguém com um iPhone. Altere três palavras nos atalhos do teclado. Por exemplo, faça de um jeito que toda vez que ele (a) apertar “Está bem” aparecer “Estou vomitando. ”",
            "Escolha alguém que deve morder uma moeda. (Mas não engula). ",
            "Escolha alguém que deverá usar apenas sinais de mão para se comunicar. ",
            "Escolha alguém que deve usar um saco na sua cabeça (com buracos para os olhos e boca) até o fim da noite. ",
            "Invente uma fofoca boba sobre alguém da sala e poste no Twitter.",
            "Faça o upload de uma foto de um tamanduá e marque alguém da sala que mais lembra um tamanduá.",
            "Escolha um jogador que só pode andar de costas pelo resto do jogador (ex. para pegar outra bebida, para ir ao banheiro). " };
    }
}
